name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: bahmutov/npm-install@master
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.3
